{
  "hash": "9a1540af53972f2e4c7282307c5a555d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"SLU Women's Rowing Winter Training Analysis 2026\"\nauthor: \"Keelin Joyce\"\ndate: \"2026-05-04\"\ncategories: [code, analysis, visualizations]\n---\n## Abstract\nThis project is an analysis of the St. Lawrence University Women's Rowing Team's winter training erg data, as well as a comparison to previous year's data. The data was collected from each erg piece during winter training and compiled into different data sets by workout. The project compares times and averages of interval pieces of varying lengths as well as creating a linear regression to predict an athlete's 2k time. It also looks at the 2k test piece progression of 2026 senior athletes. The project includes visualizations to answer questions of interest as well as detailed explanations of the trends seen.\n\n## Data and Motivation\nThe data was collected from the St. Lawrence University Women's Rowing Team during their 2026 winter training period. Training and practicing during the winter is proven to be difficult for rowing and most climates, especially the North Country, force rowers indoors for the season. The most common practice during the winter training period in rowing is the ergometer, commonly called an erg. The erg mimics the stroke that rowers take in the boat and instantly displays performance metrics to the rower. Metrics shown include the total time and distance of the workout, split per 500m (how long, in minutes and seconds, it takes the rower to complete 500m), and the stroke rate per minute.\n\nThe women's rowing team ergs five times a week and records data on each piece that they complete including interval pieces and longer steady state pieces that build fitness and test pieces that show where their performance is at. This data includes 7x500m intervals, 5x1000m intervals, 2k test pieces, and 10k test pieces.\n\n#### Variable descriptions for variables across all data sets\n| Variable | Description |\n|---------------------|---------------------------------------------------|\n| `ID` | Number indicating athlete |\n| `Average` | Average time per 500m for each interval. |\n| `IntervalX` | Average time for 500m for that interval. |\n| `Rate` | Average strokes per minute during the piece (not included in 1000s). |\n| `ClassYear` | What year the athlete is (Freshman, Sophomore, Junior, Senior) |\n| `Interval` | Which interval (of 7 or 5) the time is for. |\n| `Time` | Time (in seconds) for that interval. |\n| `Trial` | Number indicating which number trial the piece is (first of the season, second, third). |\n| `Mean` | Average time of all athletes per 500m for that interval and trial. |\n| `Name` | Number indicating athlete |\n| `Piece` | Two letters indicating class year and one digit indicating which trial of that training period. |\n| `Time` | Total time to complete 2k (in minutes:seconds) |\n| `Class` | Year of collegiate career the piece was completed during. |\n\n## Questions of Interest\n\n-   How do athletes fare during many short interval pieces compared to fewer, longer intervals?\n\n    -   is there a similar trend between 7x500 and 5x1000?\n\n    -   what could be the explanation for these trends?\n\n-   What variables best predict 2k time?\n\n    -   and what does that prediction look like?\n\n-   What does 2k progression look like over the course of a female athlete's collegiate rowing career?\n\n    -   Is the \"senior year slump\" trend upheld?\n\n\n## Data Importing\n\n::: {.cell}\n\n```{.r .cell-code}\n## initial cleaning and wrangling done in excel\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(tidyverse)\nlibrary(openintro)\nlibrary(ggeffects)\nlibrary(broom)\nx500sData <- read_csv(\"500sData2.csv\")\nx1000sData <- read_csv(\"1000sData3.csv\")\nsenior2k <- read_csv(\"Senior2k2.csv\")\n```\n:::\n\n\n## Wrangling Data for Graphing\n\n::: {.cell}\n\n```{.r .cell-code}\nx500_long <- x500sData |> pivot_longer(cols = Interval1:Interval7, \n                                       names_to = \"Interval\", values_to = \"Time\") |>\n  mutate(\"Time\" = as.numeric(Time)) |>\n  mutate(\"Time\" = Time/60) |>\n  select(ID, Average, Interval, Time, Trial)\n\nx500_line <- x500_long |> group_by(Trial, Interval) |>\n  summarise(Mean = (mean(Time)))\n  \nx1000_long <- x1000sData |> pivot_longer(cols = Interval1:Interval5, \n                                       names_to = \"Interval\", values_to = \"Time\")|>\n  mutate(\"Time\" = as.numeric(Time)) |>\n  mutate(\"Time\" = Time/60) |>\n  select(ID, Average, Interval, Time, Trial)\n\nx1000_line <- x1000_long |> group_by(Trial, Interval) |>\n  summarise(Mean = (mean(Time)))\n\npred_10k_2k <- read_csv(\"pred_10k_2k.csv\") |>\n  mutate(first10k = as.numeric(first10k)) |>\n  mutate(second10k = as.numeric(second10k)) |>\n  mutate(k2 = as.numeric(k2)) |>\n  mutate(k2 = k2/60) |>\n  mutate(first10k = first10k/60) |>\n  mutate(second10k = second10k/60) |>\n  mutate(v1 = case_when(v1 == 0 ~ \"No\", v1 == 1 ~ \"Yes\"))\n\nmod_2k <- lm(k2 ~ second10k + v1, data = pred_10k_2k)\nmod_2k |> tidy()\nglance(mod_2k)\n\nggpredict(mod_2k, terms = c(\"second10k\", \"v1\"))\nggpredict(mod_2k, terms = c(\"second10k\", \"v1\")) |> \n  as.data.frame(terms_to_colnames = TRUE) |>\n  as_tibble()\n\npred_time <- ggpredict(mod_2k, terms = c(\"second10k\",  \"v1\")) |>\n  as.data.frame(terms_to_colnames = TRUE) |>\n  as_tibble() |>\n  arrange(v1, second10k) |>\n  mutate(v1 = factor(v1, levels = c(\"No\", \"Yes\")))\n\nsenior_long <- senior2k |>\n  mutate(Name = factor(Name, labels = paste(\"Athlete\", 1:5))) |>\n  pivot_longer(\n    cols = c(FY1, FY2, FY3, SO1, SO2, SO3, SO4, JN1, JN2, JN3, SE1, SE2, SE3, SE4),\n    names_to = \"Piece\",\n    values_to = \"Time\") |>\n  mutate(Piece = factor(Piece, levels = c(\"FY1\",\"FY2\",\"FY3\",\n                                      \"SO1\",\"SO2\",\"SO3\",\"SO4\",\n                                      \"JN1\",\"JN2\",\"JN3\",\n                                      \"SE1\",\"SE2\",\"SE3\",\"SE4\")),\n    Class = case_when(str_starts(Piece, \"FY\") ~ \"Freshman\", \n                      str_starts(Piece, \"SO\") ~ \"Sophomore\",\n                      str_starts(Piece, \"JN\") ~ \"Junior\",\n                      str_starts(Piece, \"SE\") ~ \"Senior\"),\n    Piece = case_when(str_detect(Piece, \"1\") ~ \"1\",\n                      str_detect(Piece, \"2\") ~ \"2\",\n                      str_detect(Piece, \"3\") ~ \"3\",\n                      str_detect(Piece, \"4\") ~ \"4\"),\n    Class = factor(Class, levels = c(\"Freshman\",\"Sophomore\",\"Junior\",\"Senior\"))) |>\n  group_by(Name)\n```\n:::\n\n\n## Visualizations and Interpretations\n### Interval Averages\nThe team completed a 7x500m interval piece three times throughout their winter training period and a 5x1000m interval piece twice in this time. `Trial` indicates which session the piece was completed during. 7x500m means that athletes erg 500 meters as fast as they can and then rest for approximately 2 minutes before erging another 500 meters. This is repeated for 7 intervals. 5x1000m intervals were completed twice and use the same setup with a 4 minute rest between intervals.\n\nThe points show each individual data point for each interval, coloured by which trial it was completed during. The lines indicate the average of the team for each interval during each trial. They show that, in general, the team got faster each trial. A positive slope indicates a slowing down in pace as the y-axis measures total time taken to complete the interval and a higher number means a longer time.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = x500_long, aes(x = Interval, y = Time)) +\n  geom_point(aes(group = Trial, colour = factor(Trial))) +\n  geom_line(data = x500_line, aes(x = Interval, y = Mean, \n                                   group = Trial, colour = factor(Trial)), \n            linewidth = 1.5) +\n  scale_colour_viridis_d(name = \"Average of Trial:\") +\n  labs(y = \"Seconds per 500 meters\", colour = \"AverageTrial\", \n       title = \"7x500 meter Intervals\",\n       caption = \"Data collected from St. Lawrence University Crew Team Winter 2026\")+\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nOne interesting note is that, despite there being a general trend of athletes slowing down throughout the pieces, the 7th interval is a little faster than the 6th in each trial. This is most likely explained by athletes \"putting it all out there\" knowing that it is their last interval and using that to go faster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = x1000_long, aes(x = Interval, y = Time)) +\n  geom_point(aes(group = Trial, colour = factor(Trial))) +\n  geom_line(data = x1000_line, aes(x = Interval, y = Mean, \n                                   group = Trial, colour = factor(Trial)),\n            linewidth = 1.5) +\n  scale_colour_viridis_d(name = \"Average of Trial:\") +\n  labs(y = \"Seconds per 500 meters\", colour = \"AverageTrial\", \n       title = \"5x1000 meter Intervals\",\n       caption = \"Data collected from St. Lawrence University Crew Team Winter 2026\")+\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nWhile the trend for 5x1000m intervals is similar to that of 7x500m, the change in pace is not as drastic between intervals nor trials. This can be explained by the fact that the pieces are longer and athletes tire more throughout each interval (leading to a slower pace average for the interval) as opposed to slowing throughout the piece and having the interval average slow as it would in a 7x500m piece.\n\n### Linear Regression for 2k Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_2k |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic    p.value\n  <chr>          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)   79.8     55.6         1.44 0.176     \n2 second10k      0.152    0.0204      7.42 0.00000809\n3 v1Yes        -10.2      5.02       -2.03 0.0649    \n```\n\n\n:::\n:::\n\n\nThe coefficient of 0.152 for `second10k` time indicates that predicted 2k time increases, on average, by 0.15 seconds for each additional second increase in 10k time, as long as varsity boat status is held constant. This makes sense as athletes that are faster in a 10k will have generally faster 2k times, but not by the same rate as the duration of the piece impacts the pace of an athlete. \n\nThe coefficient of -10.2 for the `v1` variable indicates that athletes in the varsity boat are, on average, going to be about 10 seconds faster in their 2k than those that are not. The p-value is marginally significant but most likely reflects the smaller sample size rather than a lack of effect. The 10 second difference in time is large enough to be meaningful despite the larger p-value.\n\nThere may be cause for concern related to collinearity if you assume that varsity athletes will also have faster 10k times. This means that there is a chance that the `v1` variable would be confounded and it is important to check the correlation between the variables.\n\nAfter an analysis of the variables, it is shown that there is not a concern regarding the collinearity between the `v1` and `second10k`. The point biserial correlation between the two variables is |-0.438| which is in the ideal range of 0.3-0.7 indicating that there is no need to worry about the collinearity between variables. This is most likely due ot the fact that the varsity boat athletes are typically indicated by their 2k time and not 10k and there is a disparity in athletes that have a faster 10k compared to 2k. This is because 2k tests require more brute strength while a 10k tests the aerobic endurance of an athlete so athletes are usually higher performers in one compared to another and not both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pred_10k_2k, aes(x = second10k, y = k2)) +\n  geom_point(aes(colour = factor(v1)), alpha = 0.8) +\n  geom_line(data = pred_time, aes(x = second10k, y = predicted, \n                                  group = interaction(v1), \n                                  colour = factor(v1)), linewidth = 1) +\n  geom_ribbon(data = pred_time, aes(x = second10k, y = predicted,\n      ymin = conf.low, ymax = conf.high, group = interaction(v1),\n      fill = factor(v1)), alpha = 0.2) +\n  labs(colour = \"Varsity Boat\", fill = \"Varsity Boat\", y = \"2k time (in seconds)\",\n       caption = \"Data collected from St. Lawrence University Crew Team Winter 2026\",\n       x = \"10k time (in seconds)\", title = \"Predicting 2k time based on 10k time and Varsity Boat Status\") +\n  scale_colour_viridis_d() +\n  scale_fill_viridis_d() +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n### Analysis of 2k progression for seniors over 4 years \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = senior_long, aes(y = Time, x = Piece, group = Name, color = Name)) +\n  geom_hline(yintercept = hms::hms(minutes = 0, seconds = 0, hours = 8),\n            color = \"orange\", linewidth = 0.8, alpha = 0.8) +\n  geom_point(size = 2) +\n  geom_line() +\n  facet_grid(~ Class, scales = \"free_x\", space = \"free_x\") +\n  theme_minimal() +\n  theme() +\n  labs(x = \"Piece\", y = \"Time\", color = \"Athlete\", title = \"2k time throughout Collegiate Career by Winter Training\", subtitle = \"Looking at five individual female athletes 2023-2026\", caption = \"Data collected from St. Lawrence University Crew Team Winters 2023-2026\")+\n  scale_colour_viridis_d() +\n  theme_minimal(base_size = 12) +\n  theme(axis.text.x = element_text(size = 8))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nThe plot shows the 2k time of 5 senior athletes during each of four winter training seasons (2023, 2024, 2025, and 2026). They completed 3-4 2ks per season and it is graphed in chronological order separated by athlete. There is a general trend in which athletes get better throughout each season yet start the next year slightly slower than when they left off.\n\nOne interesting trend to examine is the idea of the \"senior year slump\". The team's coach had noticed that athletes typically performed optimally their junior year and had a regression during their senior year. This is seen in the graph as all but one athlete performed worse during their senior year as compared to their junior year. This could be due to many reasons including burnout, fatiguing, and being busier with other things and ready to move on. While there are many possible reasons for the \"senior slump\" in erg performance it is evident that it happens to athletes on the team.\n\nThe standard goal that female collegiate rowers aim for is being \"sub 8\", meaning that their 2k is less than 8 minutes. The orange horizontal line shows where this milestone is to easily compare the performance of the athletes to it.\n\n\n## Conclusion\n#### Final Analysis\nThere are many trends that can be discussed in this analysis: \n\nThere is a similar trend between 7x500 and 5x1000 meter intervals, but it can also be seen that the trend is stronger for 7x500m than 5x1000m intervals. This could be explained by the duration of the piece and the fact that athletes will tire out more during a longer interval so the averages are steadier than during a shorter distance sprint of 7x500 meters.\n\nThe most optimal prediction for 2k time uses varsity boat status and 10k time. As 10k time increases, predicted 2k time increases, but at different rates. Varsity boat members are predicted to have a faster 2k than non-varsity boat athletes. \n\n2k times typically improve over the span of the winter training period, and there is a slight increase in total time before there is another improvement. The graph supports the notion that junior year is the peak in performance of athletes, not senior year.\n\n\n#### Potential Drawbacks\nOne of the main considerations when using this data is that there is a very small sample size. The team only consists of about 20 athletes and although most complete each piece, there are still some missing data points due to injury, illness, and absences. A small sample size limits the amount of analysis that can be done.\n\nBecause the sample all came from one team there is limited variance in how the pieces are completed. This is because all of the athletes have the same coach (so they are all encouraged in the same way and have the same motivations), they are all using the same winter training schedule, and they utilize the same training facilities.\n\n#### Appendix\nThe only usage of AI in this project was to make the x-axis appropriate in the 2k progression graph. \n\nQuestion asked in Claude AI: \"How to get an individual x-axis for each facet panel in R?\"\n\nThe answer given explained that `scales = \"free_x\"` and `space = \"free_x\"` are used to have a different scale for each panel of the facet in both `facet_wrap` and `facet_grid`.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}